GET http://127.0.0.1:5001/fir-cloud-emulator/us-central1/api

###
POST https://us-central1-fir-cloud-emulator.cloudfunctions.net/api
Content-Type: application/json

{
  "name": "Harry Potter",
  "college": "Hogwarts"
}

###
DELETE https://us-central1-fir-cloud-emulator.cloudfunctions.net/api

###
PUT https://us-central1-fir-cloud-emulator.cloudfunctions.net/api